"""changes in Table

Revision ID: 480b75fb148b
Revises: 577fd5192fd0
Create Date: 2025-11-03 12:24:25.853023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '480b75fb148b'
down_revision: Union[str, Sequence[str], None] = '577fd5192fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_details', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users_details', 'hashed_password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=False)
    op.drop_index(op.f('hashed_password'), table_name='users_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('hashed_password'), 'users_details', ['hashed_password'], unique=True)
    op.alter_column('users_details', 'hashed_password',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users_details', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
